### ISSUE TITLE
Module confusing?

### ISSUE THREAD

**Issue by whoisaaronp** [offirg75/framer.RippleTransition#1]
hello,

I'm opening this conversation I regards to the 'framer.RippleTransition' Instruction. I'm having a hard time understanding 'offirg75's' explanation. 
1. For example: In the instructions below on the "framer.RippleTransition" page  it states. ' module = require("rippleModule")' But upon copying this module into my folder. The module file I put inside my folder from this project says 'android = require("rippleModule)'  not 'module' This confuses me as a newbie to using modules. which one should i use?
2. ( I'm not clear what  'top layer' & underlying layer …,  means. Can you be more specific please.)
   Your words - Create the ripple layer by calling the module function ripple(layerA, layerB, originX, originY, animationOptions)

LayerA- top layer
LayerB- underlying layer to be revealed by the ripple mask
originX- ripple X origin where it expands from
originY- ripple Y origin where it expands from
animationOptions- ripple animationOptions object (optional)

i.e. I have an 'fab' new Layer is this my 'top layer', is so what does layer B do?

**Comment by offirg75-zz** [comment]
Hi whoisaaronp, 
Happy to hear you're giving rippleModule a go. Let's see if I can resolve your issue.
1. The name of module variable doesn't really matter. It can be named whichever way you like (e.g. 'android', 'module', 'm',  etc...). Just make sure call the 'ripple' function from that module instance. I don't know why your framerjs editor would name your module variable 'andorid'. Are you working with framerjs studio? 
I suggest you look at [framerjs modules documentation](http://framerjs.com/docs/#modules.modules).
2.  rippleModule switches between two layers using a ripple affect. LayerA- the top layer is the layer that is initially on top (in the demo gif it is the blur layer). LayerB- underlying layer to be revealed by the ripple mask is the layer that is revealed once the top layer is diminished by the ripple effect (in the demo gif it is the lollipop like wallpaper) .
Take a look at the sample code https://github.com/offirg75/framer.RippleTransition/blob/master/RippleTransition.framer/app.coffee

Tx, 
Offir

**Comment by whoisaaronp** [comment]
Thanks and new year to you too for a prompt reply back.

I'm using the latest Framer studio. I changed module name from ' android = require "androidRipple" to module = require "androidRipple" I know it doesn't matter I just need to understand what's going on with out confusing my self. 

Here is my prototype.
http://share.framerjs.com/z7koj92ivoub/

I'm trying to get the 'fab' to ripple on a click event. In which case to your example, I should be using (Layer 1) and no reason to use (Layer B) ?  or…

**Comment by offirg75-zz** [comment]
Which layers are you trying to animate? which one is the top layer and which is the underlying layer.

To imagine how ripple effect works, Imagine you have a blue piece of paper on top of a green piece of paper, and the blue paper is 10 cm higher than the green. Imagine you are looking from the top of the blue piece of paper, so you only see the blue paper (and the green is hiding underneath).

The ripple effect is kind of what would happen if you would put a burning match under the blue paper and it would burn a hole from the match point to outwards and reveal the green piece of paper.

In rippleModule, the blue and green papers are the layers. The originX & originY are the point where the match started burning. 

from the code you shared, I don't understand which layers you wanted to animate.

**Comment by whoisaaronp** [comment]
I'm trying to animate the 'fab'. 

The fab or (black button with the plus symbol) - the top I guess is the 'plus symbol' and the underlying is the 'black circle' i guess?  I makes sense but confusing in order ripple examples I have seen?

i.e. https://dribbble.com/shots/2411103-MDL-x-Framer

thoughts? 
Thanks so much for your help by the way. Sorry if I sound upset. I really love framer but I'm a designer, so it's tough.

**Comment by offirg75-zz** [comment]
I now understand.

I think you need these two layers:
Fab1- your original fab button.
Fab2- similar to fab 1 but with a different background color

Something like this:

```
# Import the ripple transition module
rippleModule = require "rippleModule"

# Define the animationOptions object
animOps = {
    curve:"cubic-bezier(0.75, 0, 1, 1)"
    time:0.3
}

# Create the 2 layers to switch between
fab1 = new Layer 
    x:0, y:0, width:100, height:100, borderRadius: "50%", backgroundColor:"black"
fab2 = new Layer 
    x:0, y:0, width:100, height:100, borderRadius: "50%", backgroundColor:"blue"

# Call module to create the ripple object
ripl = rippleModule.ripple fab1, fab2, fab1.midX, fab1.midY, animOps

# On button tap, toggle the ripple's states: fill, empty
fab1.on Events.TouchEnd, (event, layer) ->
    ripl.states.next "fill", "empty"
```

Hope this helps

**Comment by whoisaaronp** [comment]
yes, I look so. Thanks very much. If I have issues I'll let you know.

peace

**Comment by whoisaaronp** [comment]
I'm getting an error offirg75. 

![screen shot 2016-01-11 at 15 23 29](https://cloud.githubusercontent.com/assets/10102392/12243913/5e822a6a-b877-11e5-82a9-b2ed2227348b.png)

**Comment by whoisaaronp** [comment]
I noticed the error was prompting ' Can't find variable' I change the name of file name in the 'module' but still another error?

**Comment by offirg75-zz** [comment]
Looks like you missed a spot:
The system looks for an object named rippleModule, but it can't find it. The object was never created.
It should have been created when required the module, however you gave the required module a different name- 'module'.

Name 'module' in line 16 to 'rippleModule' and you should be good to go.
Notice my suggestion above"

```
# Import the ripple transition module
rippleModule = require "rippleModule"
```

**Comment by whoisaaronp** [comment]
Hey offirg75, 

Good morning I was told to use -  Fab2.on(Events.Click, ripplemodule.ripple). and this will get rid of my errors. I also changed the module name to be closer to what you're doing to see if I can follow.

 http://share.framerjs.com/ng3kvdeuozz7/ 

![screen shot 2016-01-12 at 19 24 06](https://cloud.githubusercontent.com/assets/10102392/12293695/99b0a5bc-b9cb-11e5-81ec-e6c4a5f25fd0.png)

**Comment by offirg75-zz** [comment]
Hi whoisaaronp, 

I couldn't load you sample up in my Framer Studio. 
It's probably related to the fact that I have an older version (I'm not able to install the newer one).

I can only suggest you start with sample code I've provided in a separate project and once you see it working move the code to your own project.

**Comment by whoisaaronp** [comment]
hmm :( have you tried clicking updating on File > update Framer?
Do you have the purchased version?

Thats sucks. Annoying thing is that works I tried it from scratch. 
It's a great interaction too.

It's worth the pain for me.

**Comment by whoisaaronp** [comment]
OK never mind, I got it instead of: 
 ripl = rippleModule.ripple fab1, fab2, fab1.midX, fab1.midY, animals

Do: fab1.on Events.Click, rippleModule.ripple
       fab2.on Events.Click, rippleModule.ripple

http://share.framerjs.com/ijk9bb5qctmx/

**Comment by whoisaaronp** [comment]
Finally got it. 
http://share.framerjs.com/5t46fp8nq7nt/

Thanks for all your patience man

**Comment by offirg75-zz** [comment]
Congratulations!!!
Very nice work :-)
